

services:
  app:
    build: .
    container_name: bluesky-feed-generator-app
    env_file: 
      - .env
    ports:
      - "5000:5000"
    depends_on:
      - db

  db:
    image: mariadb:11
    container_name: bluesky-feed-generator-db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"